name: Main Branch and Release Tests

on:
  push:
    branches:
      - main
      - release-v*
    tags:
      - "**"

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-integration-tests:
    strategy:
      matrix:
        go-version: ["1.19", "1.20", "1.21"]
      fail-fast: false
    uses: ./.github/workflows/unit-integration-tests.yml
    with:
      go-version: ${{ matrix.go-version }}
    secrets: inherit
  multios-unit-tests:
    strategy:
      matrix:
        runs-on: [ macos-latest, windows-latest, ubuntu-latest ]
        go-version: ["1.19", "1.20", "1.21"]
      fail-fast: false
    uses: ./.github/workflows/multios-unit-tests.yml
    with:
      go-version: ${{ matrix.go-version }}
      runs-on: ${{ matrix.runs-on }}
    secrets: inherit
  slack-alert:
    runs-on: ubuntu-latest
    needs: [unit-integration-tests, multios-unit-tests]
    if: ${{ failure() }}
    name: Send Alert to Slack
    steps:
      - name: slack-send
        id: slack
        uses: 'slackapi/slack-github-action@v1.24.0'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
