name: Pull Request Tests

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  unit-integration-tests:
    strategy:
      matrix:
        go-version: ["1.17", "1.18", "1.19"]
      fail-fast: false
    uses: ./.github/workflows/unit-integration-tests.yml
    with:
      go-version: ${{ matrix.go-version }}
  multi-os-unit-integration-tests:
    strategy:
      matrix:
        runs-on: [ macos-latest, windows-latest, ubuntu-latest ]
        go-version: [ "1.17", "1.18", "1.19"]
      fail-fast: false
    uses: ./.github/workflows/multios-unit-integration-tests.yml
    with:
      go-version: ${{ matrix.go-version }}
      runs-on: ${{ matrix.runs-on }}
