name: Pull Request Tests

on:
  pull_request:
    branches:
      - "**"

jobs:
  unit-integration-tests:
    strategy:
      matrix:
        go-version: ["1.19"]
      fail-fast: false
    uses: ./.github/workflows/unit-integration-tests.yml
    with:
      go-version: ${{ matrix.go-version }}
    secrets: inherit
