name: Pull Request Tests

on:
  pull_request:
    branches:
      - "**"
  merge_group:

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-integration-tests:
    name: PR Unit and Integration Tests
    uses: ./.github/workflows/unit-integration-tests.yml
    with:
      go-version: "1.18"
    secrets: inherit
  slack-alert:
    runs-on: ubuntu-latest
    needs: [unit-integration-tests]
    if: ${{ failure() }}
    name: Send Alert to Slack
    steps:
      - name: slack-send
        id: slack
        uses: 'slackapi/slack-github-action@v1.24.0'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}