name: Unit and Integration Tests

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string

jobs:
  test-contrib:
    runs-on: ubuntu-latest
    env:
       TEST_RESULTS: /tmp/test-results # path to where test results will be saved
       INTEGRATION: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'DataDog/dd-trace-go'
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}
            #check-latest: true
            #cache: true
      - name: Test Contrib
        run: |
            go test -v -run '^$' -coverprofile=coverage.txt -covermode=atomic ./...
